name: 'Custom Semantic Release Action'
description: 'A reusable and customizable action for standardized release workflows using semantic release.'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  github-token:
    description: 'Github Token. Either the default GITHUB_TOKEN or a PAT can be used.'
    required: true
  ssh-key:
    description: 'SSH key for checkout. If provided, it will be used for checkout; otherwise, the default GITHUB_TOKEN will be used.'
    required: false
  node-version:
    description: 'Node version for setup.'
    default: '20'
    required: false
  semantic-version:
    description: 'Semantic version for release.'
    default: '21.1.1'
    required: false
  debug:
    description: 'Debug flag for semantic release (optional).'
    required: false
    default: 'true'
  dry-run:
    description: 'Whether to run semantic release in dry-run mode (optional).'
    default: 'false'
    required: false
  tag-prefix:
    description: 'Add prefix for generated Tag'
    required: false
    default: 'v'
  tag-suffix:
    description: 'Add a suffix for generated Tag'
    required: false
    default: ''
  extra-plugins:
    description: 'Additional semantic-release plugins to install (one per line). Default includes changelog and git plugins.'
    required: false
    default: |
      @semantic-release/changelog
      @semantic-release/git

outputs:
  new_release_published:
    description: 'Whether a new release was published. The return value is in the form of a string. ("true" or "false")'
    value: ${{ steps.semantic.outputs.new_release_published }}
  new_release_version:
    description: 'Version of the new release. (e.g. "1.3.0")'
    value: ${{ steps.semantic.outputs.new_release_version }}

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ inputs.ssh-key }}
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install semantic-release and plugins
      shell: bash
      run: |
        npm install --save-dev \
          semantic-release@${{ inputs.semantic-version }} \
          ${{ inputs.extra-plugins }}

    - name: Run semantic-release
      id: semantic
      shell: bash
      run: |
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          npx semantic-release --dry-run
        else
          npx semantic-release
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        DEBUG: ${{ inputs.debug }}
